name = "cf_ai_journal_coach"
main = "worker.js"
compatibility_date = "2025-10-08"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "JOURNAL_HISTORY"
id = "875fd0763f4548e8b1a604b698598d6b"
preview_id = "eb4c12fb864c4963bc05f05c81761be1"
